apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-admin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  - configmaps
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["*"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-admin-binding
subjects:
- kind: User 	
  name: sa-buckets-reader@seraphic-lock-358517.iam.gserviceaccount.com
roleRef:
  kind: ClusterRole
  name: sa-admin
  apiGroup: rbac.authorization.k8s.io
---