apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus-deployment
  namespace: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  strategy: {}
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200
      containers:
      - image: gcr.io/seraphic-lock-358517/nexus3:3.39.0
        name: nexus
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: "/nexus-data"
            name: nexus-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        #   periodSeconds: 1
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 10     
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus-svc
  namespace: shared-services
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus
  type: NodePort